image: Visual Studio 2017
clone_depth: 1
deploy: off

branches:
  only:
  - master

init:
  - cmd: git config --global core.autocrlf true

before_build:
    - cmd: dotnet restore
    
configuration:
  - Release

build_script:
  - cmd: dotnet --version
  - cmd: dotnet restore -v q
  - cmd: dotnet build -c Release -f net45 "Decorator\Decorator.csproj"
  - cmd: dotnet build -c Release -f netstandard2.0 "Decorator\Decorator.csproj"
  
test_script:
  - cmd: dotnet test -c Release /p:CollectCoverage=true Decorator.Tests\
  - ps: |
        curl -s https://codecov.io/bash > codecov
        ./codecov -f .\Decorator.Tests\coverage.json

artifacts:
 - path: 'Decorator\bin\Release\netstandard2.0\'
   name: Decorator_netstandard2.0
 - path: 'Decorator\bin\Release\net45\'
   name: Decorator_net45
   